/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MerchRouteImport } from './routes/merch'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TicketsIndexRouteImport } from './routes/tickets.index'
import { Route as TicketsOrderIdRouteImport } from './routes/tickets.$orderId'
import { Route as MerchIdRouteImport } from './routes/merch.$id'
import { Route as EventsIdRouteImport } from './routes/events.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchRoute = MerchRouteImport.update({
  id: '/merch',
  path: '/merch',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsIndexRoute = TicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsOrderIdRoute = TicketsOrderIdRouteImport.update({
  id: '/tickets/$orderId',
  path: '/tickets/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchIdRoute = MerchIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MerchRoute,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EventsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/merch': typeof MerchRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/events/$id': typeof EventsIdRoute
  '/merch/$id': typeof MerchIdRoute
  '/tickets/$orderId': typeof TicketsOrderIdRoute
  '/tickets/': typeof TicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/merch': typeof MerchRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/events/$id': typeof EventsIdRoute
  '/merch/$id': typeof MerchIdRoute
  '/tickets/$orderId': typeof TicketsOrderIdRoute
  '/tickets': typeof TicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/merch': typeof MerchRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/events/$id': typeof EventsIdRoute
  '/merch/$id': typeof MerchIdRoute
  '/tickets/$orderId': typeof TicketsOrderIdRoute
  '/tickets/': typeof TicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/events'
    | '/login'
    | '/merch'
    | '/privacy'
    | '/refunds'
    | '/signup'
    | '/terms'
    | '/events/$id'
    | '/merch/$id'
    | '/tickets/$orderId'
    | '/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/events'
    | '/login'
    | '/merch'
    | '/privacy'
    | '/refunds'
    | '/signup'
    | '/terms'
    | '/events/$id'
    | '/merch/$id'
    | '/tickets/$orderId'
    | '/tickets'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/events'
    | '/login'
    | '/merch'
    | '/privacy'
    | '/refunds'
    | '/signup'
    | '/terms'
    | '/events/$id'
    | '/merch/$id'
    | '/tickets/$orderId'
    | '/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  EventsRoute: typeof EventsRouteWithChildren
  LoginRoute: typeof LoginRoute
  MerchRoute: typeof MerchRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  RefundsRoute: typeof RefundsRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  TicketsOrderIdRoute: typeof TicketsOrderIdRoute
  TicketsIndexRoute: typeof TicketsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merch': {
      id: '/merch'
      path: '/merch'
      fullPath: '/merch'
      preLoaderRoute: typeof MerchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/': {
      id: '/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof TicketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/$orderId': {
      id: '/tickets/$orderId'
      path: '/tickets/$orderId'
      fullPath: '/tickets/$orderId'
      preLoaderRoute: typeof TicketsOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merch/$id': {
      id: '/merch/$id'
      path: '/$id'
      fullPath: '/merch/$id'
      preLoaderRoute: typeof MerchIdRouteImport
      parentRoute: typeof MerchRoute
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof EventsRoute
    }
  }
}

interface EventsRouteChildren {
  EventsIdRoute: typeof EventsIdRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsIdRoute: EventsIdRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface MerchRouteChildren {
  MerchIdRoute: typeof MerchIdRoute
}

const MerchRouteChildren: MerchRouteChildren = {
  MerchIdRoute: MerchIdRoute,
}

const MerchRouteWithChildren = MerchRoute._addFileChildren(MerchRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  EventsRoute: EventsRouteWithChildren,
  LoginRoute: LoginRoute,
  MerchRoute: MerchRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  RefundsRoute: RefundsRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  TicketsOrderIdRoute: TicketsOrderIdRoute,
  TicketsIndexRoute: TicketsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
